### ISSUE TITLE
Is there a way to get skull segmentation quickly?

### ISSUE THREAD

**Issue by HusBunia** [simnibs/simnibs#113]
Hi,
 I wonder if I can improve the efficiency of skull segmentation after some pre-processing steps have been performed. Freesurfer and data normalization have already been completed. I noticed that CHARM attempted to segment the brain and register the image to MNI space. If I have this information, can I speed up the process? In reality, I found that the CHARM's segmentation was poor because the unbiased image only included the neck and not the head.
<img width="162" alt="5" src="https://user-images.githubusercontent.com/40214939/217995417-8e265de0-1c07-473c-ac13-c746eb1d7e97.png">
<img width="163" alt="7" src="https://user-images.githubusercontent.com/40214939/217995420-b3b68e07-5728-42ce-8341-fb445b1b2c5e.png">

**Comment by oulap** [comment]
That looks like an error in the initial alignment between the charm atlas and the input scan. If you have already calculated the affine from MNI to the input you can give that to charm either using the --inittransform flag (to initialize) or the --usetransform flag (to skip the charm affine completely). See the charm help (charm -h) for details. The non-linear registration will be calculated as a part of the segmentation process, so that cannot be skipped.

**Comment by HusBunia** [comment]
> That looks like an error in the initial alignment between the charm atlas and the input scan. If you have already calculated the affine from MNI to the input you can give that to charm either using the --inittransform flag (to initialize) or the --usetransform flag (to skip the charm affine completely). See the charm help (charm -h) for details. The non-linear registration will be calculated as a part of the segmentation process, so that cannot be skipped.

Thanks for your reply .
