### ISSUE TITLE
tDCS-induced NormalE in volumes and classes

### ISSUE THREAD

**Issue by SaraRomanella** [simnibs/simnibs#134]
Hi everyone, I have a doubt about computing NormalE in tissues different than gray matter. I am using SimNIBS 4.0 to incorporate lesions in the mesh. When I run tDCS simulations I can interpolate the E-field to the surface to compute NormalE but only for the Gray Matter. 
1. How can I compute NormalE for all the tissue classes (including CSF, lesions I incorporated, etc)?
2. Can I do that for the volumes too, or only for the surface?
Thank you so much!!

**Comment by oulap** [comment]
Hi Sara,

To calculate the normal you need a surface so that you can calculate the component of the vector that is perpendicular to the surface, i.e., the normal component. At the moment the only surface we generate is the GM middle surface, which is used for the visualization and analysis of the different e-field components in the cortex. Computing the e-field components on the middle surface serves two purposes: 1) the middle GM is where we assume the stimulation effect takes place and 2) the middle surface does not suffer from outlier effects as it is distant from tissue boundaries. My point is that even if we had proper surfaces for the tissue boundaries, you probably would not want to compute the normal component right at the boundary of two tissues.
