### ISSUE TITLE
Simnibs Installation problem in BrainSight computer

### ISSUE THREAD

**Issue by XavierCorominas** [simnibs/simnibs#210]
Dear Simnibs developers,

I am contacting you because we are trying to install the latest Simnibs version in our MacOS Braisight computer and we are encountering problems in the installation. We have tried to install in with the Simnibs Installer (simnibs_installer_macos.pkg) and recived the following error : 

ImportError: dlopen(/Users/brainsight/Applications/SimNIBS-4.0/simnibs_env/lib/python3.9/site-packages/fmm3dpy/hfmm3d_fortran.cpython-39-darwin.so, 2): Symbol not found: _aligned_alloc
  Referenced from: /Users/brainsight/Applications/SimNIBS-4.0/simnibs_env/lib/python3.9/site-packages/fmm3dpy/hfmm3d_fortran.cpython-39-darwin.so
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/brainsight/Applications/SimNIBS-4.0/simnibs_env/lib/python3.9/site-packages/fmm3dpy/hfmm3d_fortran.cpython-39-darwin.so

We found a similar error when trying to install simnibs using the conda. 

Could you please orient us and help us with the installation? 

Find enclosed the .log file of the installation.
[install.log](https://github.com/simnibs/simnibs/files/12856248/install.log)

We deeply appreciate your help.

Thank you very much in advance.

Bests, 

Xavier COROMINAS.

**Comment by TorgeW** [comment]
Could you please tell us the OS version of the Mac used?

**Comment by XavierCorominas** [comment]
Hello, 

We are using currently macOS High Sierra , V 10.13.6

Thank you.

**Comment by oulap** [comment]
You can try cloning the github repo and then replacing this line in the environment_macOS.yml:

  - simnibs/external/bin/osx/fmm3dpy-1.0.0-cp39-cp39-macosx_10_9_x86_64.whl #because M1 does not like AVX
  
  with this:
  
  - fmm3dpy
  
  After that you can install simnibs following the "Installation for development" instructions in the README. 
  
  I think the problem is that you macos version is older than what we used to locally compile the fmm3dpy code with.
