### ISSUE TITLE
Option to turn off the increased resolution introduced in 4.0.1

### ISSUE THREAD

**Issue by KTZ228** [simnibs/simnibs#238]
Hello team,

I have noticed that after updating to version 4.0.1 of SimNIBS, the resolution of the segmented brain files has increased (probably related to "Tetrahedral quality of the meshes was increased substantially to improve numerical accuracy of the FEM calculations and remove outliers in the calculated electric fields"). For most people, this is probably a good thing. Nevertheless, for our specific use case, the segmentation component requires the output matrices to have the same size as the input, meaning that an increase in matrix size requires a somewhat elaborate work-around. I am left wondering whether the segmentation quality is increased and if not, if it would be possible for an option to be added to turn this off.

I might also be incorrect in my assumption that the increased matrix size of the output files is due to this new feature, so please correct me if that is the case.

Thank you for all your work.
Kenneth

**Comment by oulap** [comment]
Hi Kenneth,

The upsampled files inside the /label_prep folder are used only for meshing so that the resulting head model has good quality elements. However, the space of the mesh nodes, i.e., the coordinates, matches the world space of the original (not upsampled) input scan. There are two additional segmentation files called final_tissues.nii.gz, which includes the tissues that are in the mesh, and segmentation/labeling.nii.gz, which has more structures. Both of these files are in the same space as the original input file. So unless you have specific use for the upsampled scans under the /label_prep folder everything should be in the original space.

**Comment by oulap** [comment]
Additionally, in case you want to plug in your own segmentations. You can directly mesh those using this function:

https://simnibs.github.io/simnibs/build/html/documentation/command_line/meshmesh.html#meshmesh

The function has a flag for internally upsampling the input segmentation (--voxsize_meshing). Typically I would use a voxel size that is twice the minimum resolution of the input, for example if the input is 1mm I'd use 0.5. Again the resulting mesh nodes will be in the world space of the input.

**Comment by KTZ228** [comment]
Thank you for the quick response, I completely overlooked this. My bad.
