### ISSUE TITLE
Mesh ouput from Ernie T1 and T2

### ISSUE THREAD

**Issue by tmedani** [simnibs/simnibs#30]
Hello, 

We would like to use the Ernie data distributed within SimNibs, so we call headreco with the T1 and T2 for mesh generation, 
and we obtain this model :

![image](https://user-images.githubusercontent.com/37831900/90661303-e0a25f80-e1fb-11ea-96c0-8231fcac9011.png)

However, the expected results should be like the distributed mesh  

![image](https://user-images.githubusercontent.com/37831900/90661764-6a522d00-e1fc-11ea-9a70-e989ecabc33e.png)

Do you have an idea of what was wrong with our results?

we call this command line 

 strCall = ['headreco all --noclean  ' subjid ' ' T1Nii ' ' T2Nii];

the full function is here : https://github.com/brainstorm-tools/brainstorm3/blob/f81bda70c9ebad55d5b5ba8d472f2c054936e5ea/toolbox/process/functions/process_fem_mesh.m#L638

Thanks

**Comment by oulap** [comment]
It looks like the version of Ernie you ran does not have any neck. 
The original Ernie scans should have the neck included.

Is it possible that the input scans have been previously processed with mri2mesh? That clips the neck.

**Comment by oulap** [comment]
Hi,

You can cut the field-of-view in the z-direction so that you remove the neck slices from the input scans. 
It's easy to do with fslroi.

The neck is filled in from the probabilistic tissue template. The main reason for this is that for specific electric stimulation montages the simulated fields change quite a bit depending on if the neck is modeled or not, see:

https://core.ac.uk/download/pdf/154333674.pdf

**Comment by tmedani** [comment]
Hi @oulap 

Thanks for the explanation and for the papers.
I will check this direction.

Best,
