### ISSUE TITLE
headreco issues

### ISSUE THREAD

**Issue by mchannah13** [simnibs/simnibs#40]
Dear SimNIBS team. Firstly, thank you for such a useful program!

I have a few issues I have come across that I am hoping you can help me with. 

My main issue is with headreco, I have used this tool many times before, using t1 alone, or t1 and t2 and it has worked very well. However, I am now coming across issues and cannot create the head meshes. Either the issue seems to be "Insufficient Java memory to create the output.  Increase the Java Heap Size setting in the MATLAB preferences." Which I did, but this did not fix the problem.

Or some other examples of the issues arising are attached. Do you know how to solve any of these problems at all? I checked the .nii.gz files and they seem fine, but perhaps I am missing something. 

[slurm-4014705.pdf](https://github.com/simnibs/simnibs/files/5363415/slurm-4014705.pdf)
[slurm-4009847.pdf](https://github.com/simnibs/simnibs/files/5363416/slurm-4009847.pdf)
[slurm-4009825.pdf](https://github.com/simnibs/simnibs/files/5363417/slurm-4009825.pdf)

I also have a second question. When using the uncertainty quantification tools in Matlab, is there a way to generate images of the surfaces for mean E, sensitivities etc., using the mesh_show_surface.m function? I can view these surfaces in gmsh, but am unable to find a way to view and edit them in Matlab as you would do for the normal simulations. 

Any help would be greatly appreciated.

Many thanks for your time!

**Comment by axthi** [comment]
Hi,

could you please send the pdfs again, as they are empty documents when we open them. Maybe it's easiest when you directly send them to support@simnibs.org.

Regarding your second question: The uncertainty quantification only works on the tetrahedra. The triangle surfaces are removed in the output, and the results are stored for the gray matter tetrahedra (if you want to have additional tissues included, you will have to call the UQ via python, where you can specify which tissues you want). This is not an issue for visualization with gmsh, as it can also visualize tetrahedra, but mesh_show_surface only works for triangle surfaces.

In the following some example matlab code that reconstructs the gray matter surface from the gray matter tetrahedra and maps the results on the surface, so that you can visualize in matlab as well.

Best regards,
Axel


% ---------
clear all
close all

m=mesh_load_gmsh4('ernie_TDCS_1_gpc.msh'); 

% get surface
trep = triangulation(double(m.tetrahedra), m.nodes(:,1),m.nodes(:,2),m.nodes(:,3));
m.triangles=freeBoundary(trep);
m.triangle_regions=1002*ones(length(m.triangles),1);

% get tetrahedra connected to surface triangles
IA=[]; IB=[]; 
orders=[1 2 3;
        1 2 4;
        1 3 4;
        2 3 4];
for i=1:4
    [~,ia,ib] = intersect(sort(m.triangles,2) ,sort(m.tetrahedra(:,orders(i,:)),2),'rows');
    IA = [IA;ia];
    IB = [IB;ib];
end

% map data from tetrahedra on triangles
for i=1:length(m.element_data)
   m.element_data{i}.tridata = zeros(length(m.triangles),size(m.element_data{i}.tetdata,2));
   m.element_data{i}.tridata(IA,:) = m.element_data{i}.tetdata(IB,:);
end

mesh_show_surface(m,'field_idx','normE_mean')
mesh_show_surface(m,'field_idx','normE_std')
% ---------
