### ISSUE TITLE
simnibs_installer_linux.tar.gz download fails after ~500 MB 

### ISSUE THREAD

**Issue by connorspiech** [simnibs/simnibs#415]
The title sort of says it all. I've tried downloading the installer on Firefox, Brave, and even Chrome on my Android phone and every single time it fails once it passes the 500 MB mark. Any idea what's going on here?

**Comment by TorgeW** [comment]
Since the files are hosted on GitHub, this is sadly out of our control. 
Trying again another time might help, otherwise reaching out to the GitHub support might be your last bet. 
Your other options would be to install from source (as described here https://github.com/simnibs/simnibs) or use the whl (which is smaller) instead.

**Comment by connorspiech** [comment]
No problem, the issue turned out to be a problem with Github and my university's internet connection.
