### ISSUE TITLE
headreco vs CHARM grey matter tissue segmentation

### ISSUE THREAD

**Issue by SVH35** [simnibs/simnibs#92]
Dear SimNIBS team

Thanks for the great update to SimNIBS (i.e., 4.0 beta). I was playing around with it, comparing the performance of CHARM versus headreco based on visual inspection, and found a peculiar difference in quality of grey matter segmentation, seemingly in favor of headreco:

![image](https://user-images.githubusercontent.com/88398607/190596654-709da985-3775-4b3f-ac8a-5c8a20a070d1.png)

I used the standard headreco and CHARM (with --forceqform on) comments to run it in command prompt, and used T1w and T2s MRI scans with configurations based on Windhoff 2011 (DOI: 10.1002/hbm.21479). Could it be that I need to change my MRI scanning protocol to ensure compatibility with CHARM? Any idea what caused this issue and/or how to overcome it? 

Thanks in advance!

**Comment by oulap** [comment]
I don't think that's necessary, it's likely a matter of tweaking the charm settings a bit.
Is it possible for you to share the scans so I can have a look?
If yes, you can send a link to support@simnibs.org.

-Oula

**Comment by ggrrll** [comment]
hi, is there a follow up on this issue ? 

what would be a good sett of charm settings? 

thanks

**Comment by oulap** [comment]
In headreco the meshing is surface-driven whereas in charm we changed to volume-based meshing to accommodate new tissue types and make manual editing of the meshes easier. In charm there are a few post-processing steps to clean out the GM surface, but the output will still be different from headreco.  We are working on polishing the charm GM surface and this will hopefully be included in the next minor update of simnibs.

**Comment by oulap** [comment]
Hi Sara,

There's an option to clean out the GM using the CAT12 surfaces more aggressively, but we decided against enabling that as default as it can cut away quite a bit of gray matter. The real fix will come hopefully in the not-too-distant future once we get a bit better way of creating the GM surfaces. I've also played around with some parameter settings in order to boost the CSF a bit (again this might have some ill-effects w.r.t. other structures), see the discussion here:

https://github.com/simnibs/simnibs/discussions/131
